robot = "Aokee"

motor_dir = [1, -1, 1, -1, 1, -1]
pid_retract = [0.3, 0, 0, 0, 1.0]
retract_speed = 1.5
motor_stop_speed = 0.02
retract_ctrl_cycle_ms = 5
retract_time_min_ms = 500
joint_limit_angle = 3.49

[io]
rs485 = "/dev/serial/by-id/usb-Corecloud_Corecloud_Device-if00"

[ctrl.chassis]
cycle_ms = 5
leg_param = [0.06, 0.15, 0.22]
F_gravity = 40
pid_l_param = [1000, 2, 1000000, 10, 100]


